name: check-test-cases

on:
  push:
    paths:
      - "Development/**"
      - "Build/**"
      - "Documentation/**"

jobs:
  check-test-cases:
    name: check-test-cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run './build.cmd CheckTestCases'
        run: ./build.cmd CheckTestCases
